#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#
name: Check Required Secrets Configured

on:
  workflow_call:
    inputs:
      write_github_packages_username:
        description: 'True if the secret WRITE_GITHUB_PACKAGES_USERNAME is needed for the calling workflow'
        required: false
        default: 'false'
        type: string
      write_github_packages_token:
        description: 'True if the secret WRITE_GITHUB_PACKAGES_TOKEN is needed for the calling workflow'
        required: false
        default: 'false'
        type: string
      maven_settings_xml:
        description: 'True if the secret MAVEN_SETTINGS_XML is needed for the calling workflow'
        required: false
        default: 'false'
        type: string
      gpg_key:
        description: 'True if the secret GPG_KEY is needed for the calling workflow'
        required: false
        default: 'false'
        type: string
      gpg_keyid:
        description: 'True if the secret GPG_KEYID is needed for the calling workflow'
        required: false
        default: 'false'
        type: string
      gpg_passphrase:
        description: 'True if the secret GPG_PASSPHRASE is needed for the calling workflow'
        required: false
        default: 'false'
        type: string

jobs:
  check-write-github-packages-username-configured:
    if: ${{ inputs.write_github_packages_username == 'true' }}
    name: Check if WRITE_GITHUB_PACKAGES_USERNAME is configured
    runs-on: ubuntu-latest

    steps:
      - name: Check if WRITE_GITHUB_PACKAGES_USERNAME is set in this repository
        run: |
          if [ -z "${{ secrets.WRITE_GITHUB_PACKAGES_USERNAME }}" ]; then
            echo "WRITE_GITHUB_PACKAGES_USERNAME is not set. Please configure it in the repository secrets. \
            It must contain the GitHub username you want to use to log into GitHub Container Registry."
            exit 1
          else
            echo "WRITE_GITHUB_PACKAGES_USERNAME is set."
          fi

  check-write-github-packages-token-configured:
    if: ${{ inputs.write_github_packages_token == 'true' }}
    name: Check if WRITE_GITHUB_PACKAGES_TOKEN is configured
    runs-on: ubuntu-latest

    steps:
      - name: Check if WRITE_GITHUB_PACKAGES_TOKEN is set in this repository
        run: |
          if [ -z "${{ secrets.WRITE_GITHUB_PACKAGES_TOKEN }}" ]; then
            echo "WRITE_GITHUB_PACKAGES_TOKEN is not set. Please configure it in the repository secrets. \
            It must contain a GitHub Personal Access Token with write:packages scope \
            that you want to use to log into GitHub Container Registry."
            exit 1
          else
            echo "WRITE_GITHUB_PACKAGES_TOKEN is set."
          fi

  check-maven-settings-xml-configured:
    if: ${{ inputs.maven_settings_xml == 'true' }}
    name: Check if MAVEN_SETTINGS_XML is configured
    runs-on: ubuntu-latest

    steps:
      - name: Check if MAVEN_SETTINGS_XML is configured in this repository
        run: |
          if [ -z "${{ secrets.MAVEN_SETTINGS_XML }}" ]; then
            echo "MAVEN_SETTINGS_XML is not set. Please configure it in the repository secrets. \
            It must contain a settings.xml file containing a GPG key name and GPG passphrase. \
            Please see https://github.com/galasa-dev/galasa/blob/main/.github/templates/settings.xml for a template."
            exit 1
          else
            echo "MAVEN_SETTINGS_XML is set."
          fi

  check-gpg-key-configured:
    if: ${{ inputs.gpg_key == 'true' }}
    name: Check if GPG_KEY is configured
    runs-on: ubuntu-latest

    steps:
      - name: Check if GPG_KEY is set in this repository
        run: |
          if [ -z "${{ secrets.GPG_KEY }}" ]; then
            echo "GPG_KEY is not set. Please configure it in the repository secrets. \
            It must contain Base 64 encoded GPG key payload."
            exit 1
          else
            echo "GPG_KEY is set."
          fi

  check-gpg-keyid-configured:
    if: ${{ inputs.gpg_keyid == 'true' }}
    name: Check if GPG_KEYID is configured
    runs-on: ubuntu-latest

    steps:
      - name: Check if GPG_KEYID is set in this repository
        run: |
          if [ -z "${{ secrets.GPG_KEYID }}" ]; then
            echo "GPG_KEYID is not set. Please configure it in the repository secrets. \
            It must contain the ID of the GPG key in plain text."
            exit 1
          else
            echo "GPG_KEYID is set."
          fi

  check-gpg-passphrase-configured:
    if: ${{ inputs.gpg_passphrase == 'true' }}
    name: Check if GPG_PASSPHRASE is configured
    runs-on: ubuntu-latest

    steps:
      - name: Check if GPG_PASSPHRASE is set in this repository
        run: |
          if [ -z "${{ secrets.GPG_PASSPHRASE }}" ]; then
            echo "GPG_PASSPHRASE is not set. Please configure it in the repository secrets. \
            It must contain the passphrase for the GPG key in plain text."
            exit 1
          else
            echo "GPG_PASSPHRASE is set."
          fi