#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#
name: Check Required Secrets Configured

on:
  workflow_call:
    inputs:
      write_github_packages_username:
        description: 'True if the secret WRITE_GITHUB_PACKAGES_USERNAME is needed for the calling workflow'
        required: false
        default: 'false'
        type: string
      write_github_packages_token:
        description: 'True if the secret WRITE_GITHUB_PACKAGES_TOKEN is needed for the calling workflow'
        required: false
        default: 'false'
        type: string
      maven_settings_xml:
        description: 'True if the secret MAVEN_SETTINGS_XML is needed for the calling workflow'
        required: false
        default: 'false'
        type: string
      gpg_key:
        description: 'True if the secret GPG_KEY is needed for the calling workflow'
        required: false
        default: 'false'
        type: string
      gpg_keyid:
        description: 'True if the secret GPG_KEYID is needed for the calling workflow'
        required: false
        default: 'false'
        type: string
      gpg_passphrase:
        description: 'True if the secret GPG_PASSPHRASE is needed for the calling workflow'
        required: false
        default: 'false'
        type: string

jobs:
  check-required-secrets-configured:
    name: Check Required Secrets Configured
    runs-on: ubuntu-latest

    steps:
      - name: Check if WRITE_GITHUB_PACKAGES_USERNAME is set in this repository
        if: ${{ inputs.write_github_packages_username == 'true' }}
        continue-on-error: true
        run: |
          if [ "${{ secrets.WRITE_GITHUB_PACKAGES_USERNAME }}" = "" ]; then
            exit 1
          else
            echo "WRITE_GITHUB_PACKAGES_USERNAME is set."
          fi
        id: check-1

      - name: Check if WRITE_GITHUB_PACKAGES_TOKEN is set in this repository
        if: ${{ inputs.write_github_packages_token == 'true' }}
        continue-on-error: true
        run: |
          if [ "${{ secrets.WRITE_GITHUB_PACKAGES_TOKEN }}" = "" ]; then
            exit 1
          else
            echo "WRITE_GITHUB_PACKAGES_TOKEN is set."
          fi
        id: check-2

      - name: Check if MAVEN_SETTINGS_XML is configured in this repository
        if: ${{ inputs.maven_settings_xml == 'true' }}
        continue-on-error: true
        run: |
          if [ "${{ secrets.MAVEN_SETTINGS_XML }}" = "" ]; then
            exit 1
          else
            echo "MAVEN_SETTINGS_XML is set."
          fi
        id: check-3

      - name: Check if GPG_KEY is set in this repository
        if: ${{ inputs.gpg_key == 'true' }}
        continue-on-error: true
        run: |
          if [ "${{ secrets.GPG_KEY }}" = "" ]; then
            exit 1
          else
            echo "GPG_KEY is set."
          fi
        id: check-4

      - name: Check if GPG_KEYID is set in this repository
        if: ${{ inputs.gpg_keyid == 'true' }}
        continue-on-error: true
        run: |
          if [ "${{ secrets.GPG_KEYID }}" = "" ]; then
            exit 1
          else
            echo "GPG_KEYID is set."
          fi
        id: check-5

      - name: Check if GPG_PASSPHRASE is set in this repository
        if: ${{ inputs.gpg_passphrase == 'true' }}
        continue-on-error: true
        run: |
          if [ "${{ secrets.GPG_PASSPHRASE }}" = "" ]; then
            exit 1
          else
            echo "GPG_PASSPHRASE is set."
          fi
        id: check-6

      - name: Report which secrets are missing from repository
        if: ${{ 
          steps.check-1.outcome == 'failure' || 
          steps.check-2.outcome == 'failure' || 
          steps.check-3.outcome == 'failure' || 
          steps.check-4.outcome == 'failure' || 
          steps.check-5.outcome == 'failure' || 
          steps.check-6.outcome == 'failure' 
          }}
        run: |
          if [[ ${{ steps.check-1.outcome }} == 'failure' ]]; then
            echo "WRITE_GITHUB_PACKAGES_USERNAME is not set. Please configure it in the repository secrets.\
            It must contain the GitHub username you want to use to log into GitHub Container Registry."
          fi
          if [[ ${{ steps.check-2.outcome }} == 'failure' ]]; then
            echo "WRITE_GITHUB_PACKAGES_TOKEN is not set. Please configure it in the repository secrets.\
            It must contain a GitHub Personal Access Token with write:packages scope\
            that you want to use to log into GitHub Container Registry."
          fi
          if [[ ${{ steps.check-3.outcome }} == 'failure' ]]; then
            echo "MAVEN_SETTINGS_XML is not set. Please configure it in the repository secrets.\
            It must contain a settings.xml file containing a GPG key name and GPG passphrase.\
            Please see https://github.com/galasa-dev/galasa/blob/main/.github/templates/settings.xml for a template."
          fi
          if [[ ${{ steps.check-4.outcome }} == 'failure' ]]; then
            echo "GPG_KEY is not set. Please configure it in the repository secrets.\
            It must contain Base 64 encoded GPG key payload."
          fi
          if [[ ${{ steps.check-5.outcome }} == 'failure' ]]; then
            echo "GPG_KEYID is not set. Please configure it in the repository secrets.\
            It must contain the ID of the GPG key in plain text."
          fi
          if [[ ${{ steps.check-6.outcome }} == 'failure' ]]; then
            echo "GPG_PASSPHRASE is not set. Please configure it in the repository secrets.\
            It must contain the passphrase for the GPG key in plain text."
          fi
          exit 1
