#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#
name: Jade Test Workflow

on:
  pull_request:
    branches: [main]

jobs:

  push-to-playground-repo:
    name: Push to 'playground' repo
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout 'galasa' repo
        uses: actions/checkout@v4

      - name: Configure git, Clone target repo, Commit and Push changes
        env:
          JADE_EMAIL: ${{ secrets.JADE_EMAIL }}
          PAT: ${{ secrets.JADE_TOKEN }}
        run: |
          git config --global user.name "jadecarino"
          git config --global user.email "${{ env.JADE_EMAIL }}"
          git config user.name
          git config user.email
          git clone https://jadecarino:${{ env.PAT }}@github.com/galasa-dev/playground.git
          cd playground
          echo "This is a test file." > test.txt
          git add .
          git commit -m "Update playground repo from workflow run in 'galasa'"
          git push origin main
