#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#
name: Jade Test Workflow

on:
  push:
    branches: [jade-test-workflow]

jobs:

  push-to-playground-repo:
    name: Push to 'playground' repo
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout 'galasa' repo
        uses: actions/checkout@v4

      - name: Configure git, Clone target repo, Commit and Push changes
        env:
          PAT: ${{ secrets.GALASA_TEAM_GITHUB_TOKEN_AUTH_IN_WORKFLOWS }}
        run: |
          git config --global user.name "galasa-team"
          git config --global user.email "galasa.team@gmail.com"
          git config user.name
          git config user.email
          git clone https://galasa-team:${{ env.PAT }}@github.com/galasa-dev/playground.git
          cd playground
          git checkout -B feature-2
          echo "This is a test file." > test.txt
          git add .
          git commit -m "Update playground repo from workflow run in 'galasa'"
          git push origin feature-2
