#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#
name: IVTs PR Build

on:
  workflow_call:
    inputs:
      changed:
        description: 'True if this module has been changed and should be rebuilt'
        required: true
        type: string

jobs:

  log-unchanged:
    name: IVTs are unchanged
    if: ${{ inputs.changed == 'false' }}
    runs-on: ubuntu-latest

    steps:
      - name: Log this module is unchanged
        run: |
          echo "The IVTs module is unchanged"

  build-ivts:
    name: Build IVTs
    if: ${{ inputs.changed == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            modules/ivts

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'semeru'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.9
          cache-disabled: true

      - name: Build IVTs
        working-directory: modules/ivts/dev.galasa.ivts
        run: |
          gradle build check publish --info \
          --no-daemon --console plain \
          -PsourceMaven=https://development.galasa.dev/main/maven-repo/obr \
          -PcentralMaven=https://repo.maven.apache.org/maven2/ \
          -PtargetMaven=${{ github.workspace }}/modules/ivts/repo

      - name: Upload IVT artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ivts
          path: modules/ivts/repo

      - name: Upload IVT Test Catalog
        uses: actions/upload-artifact@v4
        with:
          name: ivts-testcatalog
          path: modules/ivts/dev.galasa.ivts/dev.galasa.ivts.obr/build/testcatalog.json

      - name: Upload IVT OBR
        uses: actions/upload-artifact@v4
        with:
          name: ivts-obr
          path: modules/ivts/dev.galasa.ivts/dev.galasa.ivts.obr/build/galasa.obr