#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#
name: Wrapping PR Build

on:
  workflow_call:
    inputs:
      changed:
        description: 'True if this module has been changed and should be rebuilt'
        required: true
        type: string
      artifact-id:
        description: 'The Workflow Run ID of the last workflow containing artifacts to download'
        required: true
        type: string

jobs:

  log-unchanged:
    name: Wrapping is unchanged
    if: ${{ inputs.changed == 'false' }}
    runs-on: ubuntu-latest

    steps:
      - name: Log this module is unchanged
        run: |
          echo "The wrapping module is unchanged"

  build-wrapping:
    name: Build Wrapping source code and Docker image
    if: ${{ inputs.changed == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            modules/wrapping
      
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'semeru'

      - name: Download platform from this workflow
        id: download-platform
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: platform
          path: modules/artifacts
  
      # If the above failed because the platform hasn't changed in this PR...
      - name: Download platform from last successful workflow
        if: ${{ steps.download-platform.outcome == 'failure' }}
        uses: actions/download-artifact@v4
        with:
          name: platform
          path: modules/artifacts
          github-token: ${{ github.token }}
          run-id: ${{ inputs.artifact-id }}

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/dev/galasa/**
          key: cache-wrapping-${{ hashFiles('**/pom.xml') }} 
          restore-keys: |
            cache-wrapping-

      - name: Building Wrapping source code
        working-directory: modules/wrapping
        run: |
          mvn deploy \
          -Dgpg.skip=true \
          -Dgalasa.source.repo=file://${{ github.workspace }}/modules/artifacts \
          -Dgalasa.central.repo=https://repo.maven.apache.org/maven2/ \
          -Dgalasa.release.repo=file:${{ github.workspace }}/modules/wrapping/repo \
          --batch-mode --errors --fail-at-end \
          --settings settings.xml

      - name: Upload wrapping artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wrapping
          path: modules/wrapping/repo